### ISSUE TITLE
Example code SyntaxError: Named export 'parseMail' not found.

### ISSUE THREAD

**Issue by amit777** [ProtonMail/jsmimeparser#2]
node versions: 16 and 18
```
npm i @protontech/jsmimeparser
```
create testmime.mjs with the code in this repo's README. I get the following error.

```
node testmime.mjs
import { parseMail } from '@protontech/jsmimeparser';
         ^^^^^^^^^
SyntaxError: Named export 'parseMail' not found. The requested module '@protontech/jsmimeparser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@protontech/jsmimeparser';
const { parseMail } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.11.0

```

I know I'm probably missing something really dumb, but any assistance would be appreciated.

**Comment by larabr** [comment]
Sorry for the delay, I didn't have notifications set up.
This is a module intended for the browser; for Node, you can look into https://github.com/nodemailer/mailparser .
Feel free to reopen if you still need help to set this up for the browser :)

**Comment by amanullah28** [comment]
@larabr I came accross same issue and I know it doesn't support CommonJs, Reason I am not using [](https://github.com/nodemailer/mailparser) because it adds unwanted information Maybe you can add support for CommonJs it will be really helpful
[](https://stackoverflow.com/questions/74937600/how-to-support-es-modules-and-commonjs-modules-at-the-same-time)

**Comment by larabr** [comment]
Sorry @amanullah28 but the lib is not currently built at all, and we have no plans of adding that step for now as it is not needed for our use-cases.
I also cannot guarantee that the lib works in a Node environment FYI, since we are only targeting and testing it in browsers.
