### ISSUE TITLE
method to stringify the MIME tree if the object is modified

### ISSUE THREAD

**Issue by amit777** [ProtonMail/jsmimeparser#3]
I was looking for a node module that has similar functionality to perl's MIME::Tools and found this one.  One of the pieces that the perl MIME::Entity can do is to `stringify()` the object and convert it back into a .eml file.    Is that type of functionality planned for this module?

**Comment by larabr** [comment]
Hi, for now we are not planning to add support for any emitter functionality, but I'll notify you if this changes :)
